volumes:
  TTTDev:

services:
  ttt:
    build: .
    ports:
      - 27015:27015/tcp
      - 27015:27015/udp
    environment:
      INSTALL_CSS: "true"
      SERVER_VOICE_ENABLE: 0
    volumes:
      - TTTDev:/home/steam/serverfiles
