#!/bin/sh

set -o errexit
set -o nounset 

imageSuffix=""
if [ "$SOURCE_BRANCH" != "master" ]; then
	imageSuffix="-$(echo "$SOURCE_BRANCH" | sed 's/\//-/g')"
fi

cd ..

bash test/testBuild.sh "$imageSuffix"

docker push "$DOCKER_REPO:gmod_debian${imageSuffix}"
docker push "$DOCKER_REPO:gmod_ttt_debian${imageSuffix}"
docker push "$DOCKER_REPO:latest${imageSuffix}"
