#!/bin/sh

#set -o errexit
#set -o pipefail
#set -o nounset 

#docker build -t "$DOCKER_REPO:lgsm_debian" "lgsm/"
cd ..
docker build -t "$DOCKER_REPO:gmod_debian" "gmod/"
docker build -t "$DOCKER_REPO:gmod_ttt_debian" "TTT/"
docker build -t "$DOCKER_REPO:latest" "TTT/"
