#!/bin/sh

set -o errexit
set -o nounset 

imageSuffix=""
if [ "$SOURCE_BRANCH" != "master" ]; then
	imageSuffix="-$(echo "$SOURCE_BRANCH" | sed 's/\//-/g')"
fi

bash test/testBuild.sh "$imageSuffix" --skip-ttt --push
